// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-01-16 15:46:28.790466463 +0900 JST m=+0.021991796

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "title": "Sample API",
        "contact": {},
        "license": {},
        "version": "1.0.0"
    },
    "paths": {
        "/rooms": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "ルーム情報を取得します",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/room"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "room": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "address": {
                    "type": "string"
                },
                "create_tx_hash": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "event_code": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_private": {
                    "type": "boolean"
                },
                "owner_address": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "wei_balance": {
                    "type": "integer"
                },
                "wei_prize": {
                    "type": "integer"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
