CREATE TABLE IF NOT EXISTS `tx_deposits` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_id` BIGINT UNSIGNED NOT NULL,
  `tx_hash` VARCHAR(255) DEFAULT NULL,
  `confirmed` TINYINT(1) DEFAULT 0,
  `success` TINYINT(1) DEFAULT 0,
  `sender` VARCHAR(255) NOT NULL DEFAULT '0x0',
  `receiver` VARCHAR(255) NOT NULL DEFAULT '0x0',
  `wei_amount` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX (`room_id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COMMENT='transaction table of deposits';

CREATE TABLE IF NOT EXISTS `tx_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `question_id` BIGINT UNSIGNED NOT NULL,
  `tx_hash` VARCHAR(255) DEFAULT NULL,
  `confirmed` TINYINT(1) DEFAULT 0,
  `success` TINYINT(1) DEFAULT 0,
  `sender` VARCHAR(255) NOT NULL DEFAULT '0x0',
  `receiver` VARCHAR(255) NOT NULL DEFAULT '0x0',
  `wei_amount` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX (`question_id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COMMENT='transaction table of payments';
